name: medicine_analyzer
description: A Flutter application to scan and analyze medicines using AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  camera: ^0.11.1
  image_picker: ^1.0.4
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  share_plus: ^10.1.4
  intl: ^0.19.0
  google_fonts: ^6.1.0  # Added for DM Sans font
  cached_network_image: ^3.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/